### ISSUE TITLE
clg doesn't have autocomplete

### ISSUE THREAD

**Issue by romokebi** [dsznajder/vscode-es7-javascript-react-snippets#102]
Overall it is a great extension, I love it!
One thing that bothers me a bit is that "clg" won't let you use autocomplete when replacing "(object)"  with an existing variable name. It usually does when you manually type "console.log()" so I wonder if that could easily be fixed?
Thank you very much.
Best,
Komo

**Comment by dsznajder** [comment]
@romokebi there is a `coo` snippet for those :)
