### ISSUE TITLE
Installing with Coc in Neovim

### ISSUE THREAD

**Issue by storypixel** [dsznajder/vscode-es7-javascript-react-snippets#103]
I just wanted to comment that I thought I was going to have to copy your repo to get your snippets but I found out luckily that with coc-snippets I could install your snippets in Vim

`:CocInstall https://github.com/dsznajder/vscode-es7-javascript-react-snippets`

I hope someone finds this useful

**Comment by zxlvera** [comment]
Would like to add anyone who is using coc-snippets after @storypixel suggestion
`:CocInstall https://github.com/dsznajder/vscode-es7-javascript-react-snippets` and still getting errors,
go to `~/.config/coc/extensions/node_modules/es7-javascript-react-snippets/` and run `yarn install --frozen-lockfile && yarn compile`.
