### ISSUE TITLE
Unable to expand emmet abbreviation together with the snippet.

### ISSUE THREAD

**Issue by mav1283** [dsznajder/vscode-es7-javascript-react-snippets#107]
Using the vscode-es7-javascript-react-snippet disables the Emmet plugin. After expanding the React prefix like for example "rfce" by pressing the tab key, I am unable to expand a div container with either an Id or class inside the component using the tab key.  Ctrl E doesn't work either. VSCode comes with Emmet, i haven't touch the settings, do i need to tweak something to make them work together?

**Comment by dsznajder** [comment]
#84

**Comment by mav1283** [comment]
Thanks for your help, i love your snippet!
