### ISSUE TITLE
version for webstorm

### ISSUE THREAD

**Issue by schealex** [dsznajder/vscode-es7-javascript-react-snippets#111]
Hi guys,

awesome snippet collection. Any plans on doing a version for webstorm?

Regards
Alex

**Comment by dsznajder** [comment]
@schealex There were plans for that long time ago but I didn't find a tool to automate creation of LiveTemplates?

**Comment by schealex** [comment]
I don't know of any tools but one would probably just need to build a tool which converts the current vscode format to the one jetbrains uses which looks like this:

```
  <template name="rafc" value="import React from 'react'&#10;&#10;export const $FILENAME$ = () =&gt; {&#10;  return &lt;div&gt;$END$&lt;/div&gt;&#10;}" description="reactArrowFunctionComponent" toReformat="false" toShortenFQNames="true">
    <variable name="FILENAME" expression="fileNameWithoutExtension()" defaultValue="" alwaysStopAt="true" />
    <context>
      <option name="ECMAScript6" value="true" />
      <option name="JAVA_SCRIPT" value="true" />
      <option name="TypeScript" value="true" />
    </context>
  </template>
```

**Comment by skylerwebdev** [comment]
@schealex Why don't you make one. I have scripts for bash that create react apps layout folders create files in them etc.

**Comment by dsznajder** [comment]
I do not have time for now to support both WebStorm & VSCode. Feel free to just copy my snippets and generate LiveTemplates
