### ISSUE TITLE
Syntax highlighting with JSX-Fragments broken, in "Javascript React" mode 

### ISSUE THREAD

**Issue by Aarbel** [dsznajder/vscode-es7-javascript-react-snippets#115]
Syntax highlighting with JSX-Fragments is broken in `Javascript React mode`.
Switching to Typescript react solves the problem, but brings the highlight mess of Typescript.

How to make it work with in  `Javascript React mode` ?

Thanks a lot for your help !

@dsznajder 

![image](https://user-images.githubusercontent.com/25119847/76690766-da53fa00-6643-11ea-8aab-09ca7c66787a.png)

![image](https://user-images.githubusercontent.com/25119847/76690772-edff6080-6643-11ea-9779-533cff1f69ec.png)

**Comment by dsznajder** [comment]
@Aarbel It's kinda not a problem of this extension, as it does not add any syntax highlight addition. You should more likely ask on the main VSCode repository or download extension which will support babel syntax probably.

**Comment by Aarbel** [comment]
@dsznajder 
thanks a lot for the tip, 

it had installed `Babel ES6/ES7 from dzannotti` and right now i installed `Babel JavaScript
from Michael McDermott` extension, it works.
