### ISSUE TITLE
Extension does not load with coc.nvim / coc-snippets

### ISSUE THREAD

**Issue by impulse** [dsznajder/vscode-es7-javascript-react-snippets#116]
> [coc.nvim] extension "es7-react-js-snippets" doesn't contain main file /Users/lynx/dotfiles/vim/.config/coc/extensions/node_modules/es7-react-js-sni
> ppets/out/index.js.

Probably an issue related to this line:
https://github.com/dsznajder/vscode-es7-javascript-react-snippets/blob/cb88c055f412078ab66c1b1613cec3c7a896e45f/package.json#L28

**Comment by dsznajder** [comment]
Why? This is output after ts transpilation.

**Comment by joshukraine** [comment]
@dsznajder I can confirm I have this same issue. (Using Neovim/coc.nvim) Plugin was working great until a few days ago. Would love to see this resolved! 🙂

**Comment by dsznajder** [comment]
I will investigate this one :)

**Comment by impulse** [comment]
@dsznajder removing the line mentioned in `package.json` makes the snippets load for me again. Dunno how if affects the build process though. Just letting you know 👍

**Comment by dsznajder** [comment]
@impulse Thank you for checking. I need to try it on my own if it works properly in VSCode too.

**Comment by pauloedurezende** [comment]
For people who are having this problem with `coc.nvim`, just access the folder where the plugin is installed (usually in `~/.config/nvim/plugged/vscode-es7-javascript-react-snippets` when installed with `vim-plug`) and run the following command:

- With Yarn
```bash
$ yarn compile
```

- With NPM
```bash
$ npm run compile
```

it will compile the package and create the file where it is expected (`./out/index.js`)

**Comment by esetnik** [comment]
Can we add a `"prepare":"npm-run-all compile"` to the `package.json` scripts section so that this happens automatically for `vim-plug` users? See https://github.com/neoclide/coc.nvim/blob/master/package.json#L16 for reference.

**Comment by pauloedurezende** [comment]
@esetnik I don't think that's is really necessary, you can make the process of compiling the package an automatic way if you use a package manager (like `vim-plug`) to install this snippet. Just add a new step into your vim/neovim when going to install the package, eg:

```
Plug 'dsznajder/vscode-es7-javascript-react-snippets', {
      \ 'do': 'yarn install --frozen-lockfile && yarn compile' }
```

**Comment by esetnik** [comment]
Ok then can we include that in the readme so `vim-plug` users know what to do. Most other vim packages I’ve used are configured to do this automatically if they require transpilation from source.

**Comment by joshukraine** [comment]
> @esetnik I don't think that's is really necessary, you can make the process of compiling the package an automatic way if you use a package manager (like `vim-plug`) to install this snippet. Just add a new step into your vim/neovim when going to install the package, eg:
> 
> ```
> Plug 'dsznajder/vscode-es7-javascript-react-snippets', {
>       \ 'do': 'yarn install --frozen-lockfile && yarn compile' }
> ```

@pauloedurezende Thanks! That worked like a charm. 🙂👍🏻

**Comment by dsznajder** [comment]
Would you like to add this to documentation somewhere in README? :)

**Comment by pauloedurezende** [comment]
@dsznajder I will open a pull request with the installation information 😄
