### ISSUE TITLE
Redux Hooks

### ISSUE THREAD

**Issue by NICHTJ3** [dsznajder/vscode-es7-javascript-react-snippets#120]
Do you have any intention of adding snippets for Redux hooks?

**Comment by dsznajder** [comment]
@NICHTJ3 but actually which? :) Most of redux-hooks are pretty easy and IMO, they do not need additionally snippets.

**Comment by victorcamnerin** [comment]
Would be awesome! Created a PR för `useSelector` and `useDispatch`. Just a proposal.

They might be easy but so is the snippet for `useState` in my opinion.

**Comment by dsznajder** [comment]
@victorcamnerin thanks for PR. I'm more likely change it to use destructuring in `useSelector` :)

**Comment by victorcamnerin** [comment]
Go for it! Cool!
