### ISSUE TITLE
Linux equivalent of cmd

### ISSUE THREAD

**Issue by Natty-Laugh** [dsznajder/vscode-es7-javascript-react-snippets#125]
Might be a dumb question but what should I use on Linux instead of cmd + shift + p. ALready tried cntrl, alt, windows button.

**Comment by dsznajder** [comment]
@Natty-Laugh I'm pretty sure `ctrl+alt+p` should be working :)
https://github.com/dsznajder/vscode-es7-javascript-react-snippets/blob/master/package.json#L42
