### ISSUE TITLE
Capitalise component names - React 

### ISSUE THREAD

**Issue by pranjaljately** [dsznajder/vscode-es7-javascript-react-snippets#128]
Currently running something like 'rfc' results in the following:
````
export default function layout() {
  return (
    <div>
      
    </div>
  )
}
````

Would it be possible for it to **capitalise** the function name either through a setting or by default resulting in:
```
export default function Layout() {
  return (
    <div>
      
    </div>
  )
}
```

The difference being between **layout** and **Layout**. (lowercase vs uppercase).
Since it is a rule/convention that ***React components must start with an uppercase letter***

**Comment by dsznajder** [comment]
@pranjaljately It's taken from the file name, So you should name your files with a capitalized letter.
