### ISSUE TITLE
VSCode Cheatsheet!

### ISSUE THREAD

**Issue by tpkahlon** [dsznajder/vscode-es7-javascript-react-snippets#129]
I built a cheat sheet using the generated Markdown file. It is an inspiration from Shopify Cheat sheet and allows to quickly go through various languages and find key shortcuts associated with each snippet. I opened this issue wondering, if you would like to add this link in Markdown file? Otherwise, you can close this issue.

[Demo](http://vscode-hacks.herokuapp.com)

**Comment by dsznajder** [comment]
@tpkahlon Hi! That's awesome! But I would like to keep it as an extension and that's why I've added build in search for this package :) You can open it with `CMD + Shift + R` on macOS
