### ISSUE TITLE
can not associate

### ISSUE THREAD

**Issue by zxf4399** [dsznajder/vscode-es7-javascript-react-snippets#131]
if i imd, then get 
import {} from 'module'
but if my project has a dependencies like 'lodash'
then can not associate

**Comment by zxf4399** [comment]
@wouterh

**Comment by devnoot** [comment]
I think I am running into the same issue.

If I do `imd->` to get `import {} from module` I don't get auto-completion on either the module or after tabbing into `{}`

**Comment by devnoot** [comment]
Just an FYI i was able to fix this issue by adding `editor.suggest.snippetsPreventQuickSuggestions` to my vscode settings
