### ISSUE TITLE
Can't see preview of snippet

### ISSUE THREAD

**Issue by Dannymx** [dsznajder/vscode-es7-javascript-react-snippets#136]
I remember recently (a few days ago) being able to see a preview of the snippet suggested, but now it's seems to be gone, is this a problem with the extension or with VScode?

![image](https://user-images.githubusercontent.com/364003/84558979-ab115f80-acfc-11ea-9489-dd6d78202e73.png)

**Comment by dsznajder** [comment]
@Dannymx I will look into, but 99% new VSCode version.

**Comment by Dannymx** [comment]
I found how to view the preview.
