### ISSUE TITLE
vim-plug is not working properly

### ISSUE THREAD

**Issue by tgkei** [dsznajder/vscode-es7-javascript-react-snippets#141]
using ```coc.nvim``` and ```vim-plug```, the following error message is shown.

```[coc.nvim] extension "es7-react-js-snippets" doesn't contain main file```

I can see the repository is successfully installed in autoload folder, so in ```.config/nvim/autoload/plugged/vscode-es7-javascript-react-snippets``` the folder exists, but according to the error message, in this folder, there should be ```out/index.js```, but there is no such folder and file

**Comment by dsznajder** [comment]
Please look here #103 and check if you have a proper setup. I do not use `coc.nvim` so I can't test it by myself but seems like this solves an issue.
```
Plug 'dsznajder/vscode-es7-javascript-react-snippets', {
      \ 'do': 'yarn install --frozen-lockfile && yarn compile' }
```

**Comment by tgkei** [comment]
@dsznajder it might be silly question but how can I trigger the snippet?? using ```tab```? Again sorry for silly question and thx for good reply

**Comment by dsznajder** [comment]
@tgkei Could you provide some error stack for that?

**Comment by tgkei** [comment]
> @tgkei Could you provide some error stack for that?
> When it comes to trigger snippets it depends on your setup. You can configure VSCode for `tab` trigger but there is also search for snippets.

Sorry for my Coc setting had some issues. After fixed coc everything works fine thx!

**Comment by maharjanaman** [comment]
@tgkei I'm having a similar issue. What was your issue in coc settings?

**Comment by ScriptAlchemist** [comment]
@tgkei do you mind sharing was you changed in the Coc setting? I'm also curious on this setup. I think I'm going to just use VScode for next.js right now, but I'd love to have this in vim.
