### ISSUE TITLE
formatting issue

### ISSUE THREAD

**Issue by Snivio** [dsznajder/vscode-es7-javascript-react-snippets#148]
I have prettier configured for formatting but if i have this the "es7-javascript-react-snippets" enabled and format on save enabled.
if i try save a CSS file it says cannot format with es7-javascript-react-snippets. but if i turn this plugin of pretter works properly with css format (Only happens for CSS formating)

**Comment by dsznajder** [comment]
@Snivio shouldn't be problem as it now only applied to .ts{x} and .js{x} files
