### ISSUE TITLE
Hooks snippets interfere with auto-importing hooks

### ISSUE THREAD

**Issue by dantman** [dsznajder/vscode-es7-javascript-react-snippets#150]
This extension appears to have undocumented snippets related to hooks. These hooks appear to use the hook names rather than shortcut names (like the `ueh` an extension I actually use for this purpose provides).

This is problematic because for some hooks when you try to auto-import a hook from react the first intellisense entry that shows up is the snippet instead of the auto-import.

i.e. This mess is what I get when trying to auto-import `useEffect` when this extension is installed.
<img width="799" alt="Screen Shot 2020-10-20 at 8 27 57 PM" src="https://user-images.githubusercontent.com/53399/96669940-1e625800-1313-11eb-9aa9-7b65cfacb3f7.png">

**Comment by dsznajder** [comment]
@dantman They are documented [here](https://github.com/dsznajder/vscode-es7-javascript-react-snippets#react-hooks). If you would like change order, just change your VSCode settings.
