### ISSUE TITLE
rxreducer eslint warning

### ISSUE THREAD

**Issue by AlbinCederblad** [dsznajder/vscode-es7-javascript-react-snippets#155]
eslint gives warning: "Assign arrow function to a variable before exporting as module default"

https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-anonymous-default-export.md

**Comment by dsznajder** [comment]
@AlbinCederblad This extension won't support every eslint config & plugin which exists :) Consider changing your own config. I'm also happy to change it but it would need 2 snippets, one for creating a function, and another one, with export of this function.
