### ISSUE TITLE
TypeScript type & interface Props configuration

### ISSUE THREAD

**Issue by talohana** [dsznajder/vscode-es7-javascript-react-snippets#157]
TypeScript allows to model types with 2 options - a type and an interface.

A comparison between the two can be found in [this blogpost](https://blog.logrocket.com/types-vs-interfaces-in-typescript/)
Is there an option to change the TypeScript snippets to use types instead of interfaces when declaring the `Props`  type?

For example instead of generating with `tsrafc`

```tsx
interface Props {}

export const Example = (props: Props) => <> ... </>;
```

to generate

```tsx
type Props = {};

export const Example = (props: Props) => <> ... </>;
```

**Comment by dsznajder** [comment]
@talohana There is #62 an issue to track those. Unfortunately I didn't have time to look how to implement those options and then apply changes to `json` files. I thought of some placeholders and then replacing with proper value i.e.:

Option with select options: Interface / Props 

and then based on this value replace all occurrences of this placeholder in snippets, but it would also force users to restart whole VSCode as snippets are loaded on start AFAIK.

**Comment by andrewphamvk** [comment]
Since I'm the only user on my machine, editing C:\Users\{user}\.vscode\extensions\dsznajder.es7-react-js-snippets-3.1.1\snippets\ts-snippets.json and replacing _interface_ with _type_ is a good work around.

**Comment by talohana** [comment]
> Editing C:\Users{user}.vscode\extensions\dsznajder.es7-react-js-snippets-3.1.1\snippets\ts-snippets.json and replacing `interface` with `type` and adding the additional `=` is a good workaround.

Is there a way to save this change with vscode settings sync?

**Comment by dsznajder** [comment]
Tracked in #185
