### ISSUE TITLE
Feature request: MyComponent.propTypes and MyComponent.defaultProps

### ISSUE THREAD

**Issue by MikeBruns** [dsznajder/vscode-es7-javascript-react-snippets#159]
Really enjoy the extension, especially for typing out props ❤️

I have a feature suggestion I find myself wanting. I would like to have a snippet for just the `propTypes` and `defaultProps` objects after I've already created the class.

### MyComponent.propTypes 
```javascript
MyComponent.propTypes = { }
```
### MyComponent.defaultProps
```javascript
MyComponent.defaultProps = { }
```

If applicable, here is the code I was thinking of for the snippets. I wanted to make sure it's a desired feature before making a PR :)
Commit: https://github.com/MikeBruns/vscode-es7-javascript-react-snippets/commit/908e94ea0e1a441758a32b1db2470e71af471690

**Comment by dsznajder** [comment]
I personally feel like `MyComponent.defaultProps` is something to avoid in projects. `.propTypes` could be useful tho for people that are not on TS. I will try to provide it in the next version as I have somehow a clear idea for extension settings.
