### ISSUE TITLE
Extension prevents the auto imports of all react hooks and is dated / overly opinionated RE syntax of snippets

### ISSUE THREAD

**Issue by Mr0cket** [dsznajder/vscode-es7-javascript-react-snippets#163]
This extension blocks VScode inline auto import suggestion for react imports, e.g 'useState' and 'useCallback' etc.
The auto import suggestions are a really useful feature, and saves more time than is saved by using the snippet (especially in long files where you need to scroll to the very top in order to import the hook).

Demonstration with snippets disabled:

https://user-images.githubusercontent.com/56648742/103542741-adf0bf00-4e9d-11eb-802e-db36463e4189.mov

with snippets enabled

https://user-images.githubusercontent.com/56648742/103543004-18096400-4e9e-11eb-8b45-0a45e3c8e642.mov

**Comment by Mr0cket** [comment]
Whoops, those videos a bit bigger than I expected...

**Comment by dsznajder** [comment]
@Mr0cket Yes, I'm aware of that but it's not possible to trigger auto-import with a snippet unfortunately AFAIK.

**Comment by Mr0cket** [comment]
I actually prefer if I could disable those specific snippets so that I can use auto-import and still use this extension. is that possible?

**Comment by Mr0cket** [comment]
Is it possible to disable or remove individual snippets from the extension so that they don't interfere with the Auto import functionality?
