### ISSUE TITLE
[suggestion]: don't add props for tsr[a]fc[e] , utilize tsrafcp instead?

### ISSUE THREAD

**Issue by marcebdev** [dsznajder/vscode-es7-javascript-react-snippets#164]
I believe it'd be helpful to have `tsrafc`, `tsrafce`, `tsrfc`, `tsrfce` not add React props as the snippet adds an interface and props which can't really be auto removed by eslint, at least not reliably if even possible.

Doesn't seem like this has been suggested before and I've recently started using TS so idk maybe I'm the odd one out or I'm missing something, but seems practical. For instance if I'm creating the root component for a page depending on the page I more often than not either won't need root level props until later enough I'd rather not start with them there or simply don't need them.

It'd be a general quality of life improvement and more consistent with how the non-ts snippets work (`rafc`, `rafce`, `rafcp`). Sure the `tsrafcp` behavior would arguably be slightly different but at the prior two would be more consistent and allow the ability to create the a snippet without props.

**Comment by dsznajder** [comment]
I will make some changes related to those snippets but I need to figure out settings and the rest of stuff that is dynamic or workspace specific (i.e. `type` over `interface` etc.)
