### ISSUE TITLE
Snippets don't work anymore!

### ISSUE THREAD

**Issue by AyazAI** [dsznajder/vscode-es7-javascript-react-snippets#174]
When i try extension snippet the shortcut don't work anymore.
e.g when i do `rafce` it returns no snippet code.

![don'twork](https://user-images.githubusercontent.com/45338553/113511377-ec6b4800-9578-11eb-87c4-f71cdd8c51cd.png)

`code -v`
`1.55.0
c185983a683d14c396952dd432459097bc7f757f
x64
`

**Comment by dsznajder** [comment]
@AyazAI Please check your VSCode settings. You've probably removed snippets suggestions in options.

**Comment by AyazAI** [comment]
@dsznajder Thanks! I had to enable and disable Emmet suggestions then it worked!
