### ISSUE TITLE
It stopped working

### ISSUE THREAD

**Issue by danieltkach** [dsznajder/vscode-es7-javascript-react-snippets#181]
It just stopped working after a VS Code update. I tried uninstalling, restarting, then installing it from the browser marketplace, and from VS Code itself. I uninstalled other extensions for snippets and tried all over again, and nothing. I don't know what else to try, and I'd really like this to work again. Any ideas what I can do?
Thanks.

**Comment by Nick-HK** [comment]
@danieltkach , Can you provide the details like the version of the plugin and the version of the VS Code? Thanks!
