### ISSUE TITLE
The React Hooks section in README.md is not useful at all

### ISSUE THREAD

**Issue by silviubogan** [dsznajder/vscode-es7-javascript-react-snippets#184]
And it looks broken, it is talking about React Native in its table.

https://github.com/dsznajder/vscode-es7-javascript-react-snippets#react-hooks

Could you guide me to some resource talking about React hooks in this VSCode extension?

Thanks for the hard work!

**Comment by AbundantSalmon** [comment]
It basically says you can call all the snippets by their hook names, i.e. `useMemo` will expand to `useMemo(() => function, input)`
