### ISSUE TITLE
Can't find extension on gitpod

### ISSUE THREAD

**Issue by nwazuo** [dsznajder/vscode-es7-javascript-react-snippets#193]
Somehow I can't find this extension when searching for it in the extensions tab in VSCode for https://gitpod.io 

Is there a way to work around this? By maybe getting a snippet file of all the snippets in this extension while we hopefully wait for a variation of the extension that works for gitpod.io ?

**Comment by dsznajder** [comment]
I do not know the tool but I have zero control and experience on gitpod.io
