### ISSUE TITLE
How to change a snippet -> remove the object in the clg shortcut?

### ISSUE THREAD

**Issue by aindriu80** [dsznajder/vscode-es7-javascript-react-snippets#197]
Hi,

How do you remove the object in the console line shortcut or create a shortcut without the object there?  When you type clg you get the following:-

`console.log(object)`

I want the following:-

`console.log()`

Often when I am using console.log I am using it to print quotes out and then something else, once I type clg and then quotes I get:

`console.log("object")`

The problem is that I have to manually delete what's in the quotes and it's too much effort.  Also, when using the clo shortcut the second tab brings you outside the ) bracket and not after the comma with the object highlighted.

`console.log(`object`, object)`

**Comment by dsznajder** [comment]
`clg` is for `console.log($1)`, you can tap TAB to go to those parents. for `console.log("object", object)` go with `clo`

**Comment by aindriu80** [comment]
I don't think you read my post, 

I am NOT looking for object at all.

How do you REMOVE the object in the shortcut?
