### ISSUE TITLE
Fetching Incorrect filename 

### ISSUE THREAD

**Issue by yashrajbothra** [dsznajder/vscode-es7-javascript-react-snippets#204]
Soo I was using react and while using rfc snippet the function name was not matching.

Steps to reproduce 

1. Create new file and name it anything ex :- (Example)
2. Create rfc using rfc
2. Now change the filename
3. Now Delete the code and try again...LOOP...

https://user-images.githubusercontent.com/47683556/148680552-1bdd074f-c9de-472c-baa0-7d457170dad2.mp4

**Comment by dsznajder** [comment]
@yashrajbothra snippets are using filename variable directly from VSCode so if it's not working properly, you should open issue in editor repo instead. https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables
