### ISSUE TITLE
Mobx snippet?

### ISSUE THREAD

**Issue by Taym95** [dsznajder/vscode-es7-javascript-react-snippets#24]
Can we add mobx import's snippet?

**Comment by dsznajder** [comment]
Sure we can, but I'm not very fluent with mobx. Have you some experience with that / patterns etc. Articles / docs welcomed 💃

**Comment by Taym95** [comment]
Yes, I will try to submit PR.

**Comment by dsznajder** [comment]
Great :)

**Comment by dsznajder** [comment]
Seems to be stale, let me know if you still need those :)
