### ISSUE TITLE
Disable import React from 'react'

### ISSUE THREAD

**Issue by chadleong** [dsznajder/vscode-es7-javascript-react-snippets#275]
Since this statement is no longer needed in React 17+, can this be disabled while using `rafce`

**Comment by totti-rdz** [comment]
In the extension settings there is a setting called  "Import React On Top" that "controls if snippets should add import React from 'react'; at the top of components. Use if you have React +17 and use jsx transform."
I'm pretty sure, you're looking for that.

PS. works on VS Code

**Comment by chadleong** [comment]
Thanks that does the trick !
