### ISSUE TITLE
add indention options

### ISSUE THREAD

**Issue by WadhahEssam** [dsznajder/vscode-es7-javascript-react-snippets#28]
you use 2 spaces indention while vs code default is 4 so i need to re-indent the snippets

**Comment by dsznajder** [comment]
@WadhahEssam Sorry for late response, I will today investigate this if this is possible with snippet extension :)

**Comment by dsznajder** [comment]
@WadhahEssam Unfortunately I did not found anything for snippets option, If you have any advice on that related especially for snippets just leave a comment.
