### ISSUE TITLE
React Hooks Snippets

### ISSUE THREAD

**Issue by awongCM** [dsznajder/vscode-es7-javascript-react-snippets#36]
Any plans for providing snippets of [React Hooks](https://reactjs.org/docs/hooks-intro.html) in the future?

**Comment by dsznajder** [comment]
Yes, I have it locally but until it will be released officially, I won't publish those :)

**Comment by awongCM** [comment]
Hehe. I could hardly wait..! Thank you! 😄

**Comment by dsznajder** [comment]
I hope they won't change API :D

**Comment by awongCM** [comment]
Let's hope so too! XD
