### ISSUE TITLE
clo→ console.log("Object", Object);

### ISSUE THREAD

**Issue by DevPolo** [dsznajder/vscode-es7-javascript-react-snippets#42]
Hi,
First, thank you for your work ;)
Could you add a new command like: 

`clo→ console.log("Object", Object);`

to console.log with two cursors?

Thank you so much ;)

**Comment by DevPolo** [comment]
Hi,
First, thank you for your work ;)
Could you add a new command like: 

`clo→ console.log("Object", Object);`

to console.log with two cursors?

Thank you so much ;)

**Comment by dsznajder** [comment]
Of course! Good idea :) I will add this even today :)

**Comment by DevPolo** [comment]
Thank you so much :D

**Comment by dsznajder** [comment]
@DevPolo Published in `1.9.3`
