### ISSUE TITLE
Optimized for TypeScript

### ISSUE THREAD

**Issue by TetsuyaNegishi** [dsznajder/vscode-es7-javascript-react-snippets#46]
Hello,
Thank you for a wonderful extension.

I am making an application that reacts with TypeScript.
But, this extension is not optimized for TypeScript.

For example,
`` `
// js
import React from 'react'

/ / ts
import * as React from 'react'
`` `

I would like to fork this repository and create an extension optimized for TypeScript.
And I want to distribute it on the market.
(Of course I will follow [LICENCE](https://github.com/dsznajder/vscode-es7-javascript-react-snippets/blob/master/LICENCE))

Is it OK?

Thank you for reading.

**Comment by dsznajder** [comment]
Hi :) No problem at all, you can fork and optimize this one for TS :)

**Comment by TetsuyaNegishi** [comment]
Thank you!
