### ISSUE TITLE
curly brace after a function name is invoking imrc command

### ISSUE THREAD

**Issue by RatnadeepBiswakarma** [dsznajder/vscode-es7-javascript-react-snippets#47]
for few days I'm getting one issue with this snippet in VS Code, whenever I'm typing `{}` after any function name of method name followed by `()`  in `js` or `jsx` file it's invoking `imrc` command and import statement  popping up and hitting enter expanding to import statement rather than breaking to next line
![react plugins issue](https://user-images.githubusercontent.com/36644040/50423063-5bc04080-0876-11e9-8b6a-f09c276a2507.png)

**Comment by dsznajder** [comment]
@RatnadeepBiswakarma I believe it's not a problem with this extension but with VSCode. Just open similar issue on main repo and let people check the config :)
