### ISSUE TITLE
componentDidMount wrong syntax

### ISSUE THREAD

**Issue by monastyrskiiden** [dsznajder/vscode-es7-javascript-react-snippets#48]
**Hey, currently You're using arrow syntax:**

```
cwm→ | componentWillMount = () => { } DEPRECATED!!!
cdm→ | componentDidMount = () => { }
cwr→ | componentWillReceiveProps = (nextProps) => { } DEPRECATED!!!
scu→ | shouldComponentUpdate = (nextProps, nextState) => { }
cwup→ | componentWillUpdate = (nextProps, nextState) => { } DEPRECATED!!!
cdup→ | componentDidUpdate = (prevProps, prevState) => { }
cwun→ | componentWillUnmount = () => { }
```
**But all these methods using simple function declaration syntax like so:**

``
componentDidMount(){}
``
**Please fix this issue.**

**Comment by dsznajder** [comment]
@monastyrskiiden Why is this problem for you actually? It does not cause an error.

**Comment by monastyrskiiden** [comment]
> @monastyrskiiden Why is this problem for you actually? It does not cause an error.

Actually it does. Maybe it's just my webpack configuration, but in my opinion, the better way is to follow the default syntax. **In this particular case i've used** `componentDidMount = () => {}`
![error](https://user-images.githubusercontent.com/26526916/50575190-aeaf7000-0e01-11e9-80f2-30028424fd4c.png)

**Comment by dsznajder** [comment]
@monastyrskiiden Yes, it's problem with your webpack config. I won't change this syntax as I like to keep things consistent with the rest of package. 
Closing for now.
