### ISSUE TITLE
Quick use of snippet shortcuts

### ISSUE THREAD

**Issue by KevinHerklotz** [dsznajder/vscode-es7-javascript-react-snippets#55]
I'm used to use [Emmet](https://emmet.io/) where I could just enter a shortcut and then press `Tab`.
With the `vscode-es7-javascript-react-snippets` this is not possible for me. I first have to press `CMD + Shift + P`, then start to type `ES7 snippet search` then press `Enter` and then type the shortcut and then press `Enter` again.
Within this time I would have typed the command myself.
So either this feature does not exist, then this Issue would be a **feature request**
OR this feature does exist, then this Issue would be a **documentation update request**, because it is not documented anywhere how I can make this Extension work with `Tab`.

(I tried it in a `jsx` file Using VSCode Version 1.31.1)

Thanks for your help 🙏

**Comment by dsznajder** [comment]
It's possible in emmet because of `Emmet: Trigger Expansion On Tab` setting.
It's actually features request :) I will look into this in my free time. You can also bind `ES7 snippet search`

**Comment by dsznajder** [comment]
@KevinHerklotz I've added `CMD + Shift + R` keybinding for Snippet Search. I'm closing an issue for now. If there is anything that I missed just write it here and I will reopen.
