### ISSUE TITLE
There is no difference between `rafc` and `rafce`

### ISSUE THREAD

**Issue by in-in** [dsznajder/vscode-es7-javascript-react-snippets#56]
I think there is a reason for this :thinking: but I can't get it.

https://github.com/dsznajder/vscode-es7-javascript-react-snippets/blob/628e0d4df8e2e791c8a1e08d6c95d9718669ee03/snippets/snippets.json#L334

https://github.com/dsznajder/vscode-es7-javascript-react-snippets/blob/628e0d4df8e2e791c8a1e08d6c95d9718669ee03/snippets/snippets.json#L352

![190561551086305](https://user-images.githubusercontent.com/8797432/53326799-7dca5380-38f7-11e9-8f1f-dda2d170914a.png)

**Comment by dsznajder** [comment]
It's just backwards compatibility as it does not make sense to create functional component without name:
```js
export default () => {
	return <div>...</div>
}
```
