### ISSUE TITLE
Hooks snippets

### ISSUE THREAD

**Issue by yuritoledo** [dsznajder/vscode-es7-javascript-react-snippets#57]
Hello!

Do you pretend to add some Hooks snippets?

Thanks!

**Comment by dsznajder** [comment]
Yes, I will add them in some free time :)

**Comment by dsznajder** [comment]
Shipped in `2.1.0`

**Comment by pubgrad** [comment]
In the docs there is nothing that tells us how to use it other than it uses hook name prefix. What does that mean?

**Comment by dsznajder** [comment]
@pubgrad that means if hook exist like: ‚useState’ then snippet is called ‚useState’ and go on :) Yeah, docs could be better but i do not have time currently to improve it. If you find it hard just raise and issue or help me with PR :)

**Comment by pubgrad** [comment]
@dsznajder Thanks for the response. Is there a way I can edit any snippet. For a functional component the snippet is rfc, but I would love to edit it so that it imports {useState} with React from 'react'

**Comment by dsznajder** [comment]
@pubgrad you can create your own :)

Go and checkout docs on VS Code site :)
