### ISSUE TITLE
Intellisense doesn't work

### ISSUE THREAD

**Issue by jdahdah** [dsznajder/vscode-es7-javascript-react-snippets#61]
It appears that there is an issue with Intellisense for npm packages.

Using the `imp` snippet does not provide Intellisense auto-completion. Typing a regular import statement by hand does. I'm not sure what the root cause is. Here's a video of the issue:

https://www.youtube.com/watch?v=QOi44GXGJy0

**Comment by dsznajder** [comment]
@jdahdah Woah, thanks for best reproduction I've ever seen :) However, I do not know what is happening and actually why. I will try to figure it out and search through VSCode issues. Maybe I will find something. 

Thanks for reporting issue.

**Comment by jdahdah** [comment]
Cheers! Let me know if I can provide any further information.

**Comment by polishedwp** [comment]
FYI. I reverted back to VSCode 1.32.3 (February 2019) version and everything works fine. It appears the March release broke Intellisense with snippets.

**Comment by dsznajder** [comment]
@polishedwp Could you write this inside issue I've opened? :)

**Comment by polishedwp** [comment]
Just did. Thanks

**Comment by polishedwp** [comment]
So the suggestion from VSCODE was to use `editor.suggest.snippetsPreventQuickSuggestions`.
I did add to the settings.json and set to `false`. Snippets still don't really work. 

As you can see, it still presents the loading:
![Screen Shot 2019-04-09 at 5 45 54 AM](https://user-images.githubusercontent.com/13651291/55791139-dad72e80-5a8b-11e9-8d47-f0cc2bab557a.png)

The template eventually works, after a VERY long delay (at least a minute), inserting the snippet but autocomplete is unusable. 
![Screen Shot 2019-04-09 at 5 50 53 AM](https://user-images.githubusercontent.com/13651291/55791212-ffcba180-5a8b-11e9-85ad-aedb48cfbc6a.png)

**Comment by dsznajder** [comment]
@polishedwp I've tested this on my own, and it works fine. I think it's more related now to the VSCode performance, size of Component / Project and your own hardware.

For everyone that is trying to figure it out: 
![Screenshot 2019-04-09 at 13 10 38](https://user-images.githubusercontent.com/17621507/55795808-e6951600-5ac8-11e9-8124-053cb0827cca.png)

Your settings related to snippets suggestions should look like this.

**Comment by polishedwp** [comment]
Thank @dsznajder but that is my setting as indicated above. I am working on a small gatsbyjs starter so the project is small, and the only think that changed as VSCode. As long as I use VSCode 1.32.3 (February 2019) version everything is fine. But I am not sure this is your problem.

**Comment by dsznajder** [comment]
@polishedwp I will try to track issue on VSCode. If there will be no answer from their side, I would propose to open another issue in their repo.

**Comment by polishedwp** [comment]
Thank you ... for what it's worth a new issue was opened [today](https://github.com/Microsoft/vscode/issues/71998) which point corroborates an issue with this release of VSC.

**Comment by polishedwp** [comment]
Final report for those that might experience this problem. The issue is the version of Typescript used with VSC 1.33. To fix the problem, install Typescript 3.3.3. Look here for detailed instructions at [Stackoverflow](https://stackoverflow.com/questions/39668731/what-typescript-version-is-visual-studio-code-using-how-to-update-it) on how to change TS versions in VSC.

**Comment by jdahdah** [comment]
Forcing VSCode to to use TypeScript 3.3.3333 worked for me, too. Thanks @polishedwp.
