### ISSUE TITLE
Semi & singleQuotes configuration - [Not available for now]

### ISSUE THREAD

**Issue by sravan-s** [dsznajder/vscode-es7-javascript-react-snippets#62]
Hi @dsznajder, thanks for making this nice plugin. Is there an existing way to use double quotes instead of single quotes and to add semicolons?

Example -> 

```
import React, { PureComponent } from "react";
import PropTypes from "prop-types";

export default class TaskInformation extends PureComponent {
  static propTypes = {

  }

  render() {
    return (
      <div>
        
      </div>
    );
  }
}
```

**Comment by dsznajder** [comment]
There is no possibility for now, but feel free to add this option :)

**Comment by sravan-s** [comment]
I didn't check the code base yet, I will try anyways :)

**Comment by Rc85** [comment]
Single quotes is based on your vscode settings.

**Comment by ReasonableDeveloper** [comment]
I'm not sure if you need this feature inside the library for another reason but there is always the possibility to have `prettier` autoformat your code based on your project preferences.

1. Insert snippet
2. Save document with prettier installed or format code via the command palette `CTRL|CMD+Shift+P => Format Document`

**Comment by dsznajder** [comment]
@ReasonableDeveloper Sure, but would be nice if someone could do it without some onSave hook / format document. I'm also looking forward to add some other specific settings as `// @flow` annotation, etc. I will check once more if anything has changed

**Comment by Rc85** [comment]
For semi-colons, it is possible by editing snippets.json. However, not all users prefer semi-colons.

**Comment by fauzanelka** [comment]
It would be good if you add this as an option. If it turned on it will add semicolon, vice versa.

**Comment by trailofdad** [comment]
I'd like to see this as an option as well. I've never contributed before but this seems like it might be a good first issue 😄

**Comment by dsznajder** [comment]
@trailofdad The problem is, I didn't see any options to pass them into `snippets.json` file. This extension already contain some options and commands already so it won't be a problem to set them but, can't read them on side of template.

**Comment by trailofdad** [comment]
@dsznajder Forgive me if this is a silly idea, because I have no experience with plugin dev at the moment. Would be be possible to do a string replace on the single quotes when you convert the JSON to a string? Lets say if a flag were set in the settings or something?

**Comment by dsznajder** [comment]
I thought about same thing. I’m not sure about performance downsize of that. Also, change of this any of those, should regenerate .json file everytime, not sure if possible to dynamically lod new file. I will it over the weekend.

P.S. I’m not familiar with extension development neither ;p just reading docs and trying.

**Comment by trailofdad** [comment]
@dsznajder Awesome 😎 I'll have a look at it when I have a chance as well 🚀

**Comment by dsznajder** [comment]
@trailofdad I've tried the approach which we discussed, unfortunately I didn't achieve the expected result. `active` function only is applied when command for search is triggered, and I did not found any other solution in docs (maybe I've missed something). Additionally, `.json` files are loaded on very beginning (their paths are declared in `package.json`).

**Comment by WispAmulet** [comment]
I found this plugin has options to decide whether to use semicolons or not. The plugin works for now but it seems that it's no longer being manitained by its owner.
Maybe someone would check this. [React Redux ES6 Snippets](https://marketplace.visualstudio.com/items?itemName=timothymclane.react-redux-es6-snippets)

**Comment by AmodeusR** [comment]
So you guys just gave up on this idea?

**Comment by dsznajder** [comment]
I finally found some time to play around with this. Unfortunately, It's still very limited but it's working for snippets from search. Hope so for now it will be enough but still looking into the possibility of dynamically loading inline prompts and applying format
