### ISSUE TITLE
useState still wrong

### ISSUE THREAD

**Issue by yuritoledo** [dsznajder/vscode-es7-javascript-react-snippets#64]
Hey man!

have you updated the vscode theme on editor? the `useState`still are with problem:

![image](https://user-images.githubusercontent.com/18474538/55084027-44fed500-5083-11e9-9b48-8627a741d4ba.png)

The initialState are not get the 2nd bind `${2:initialState}`

Thank you :)

**Comment by dsznajder** [comment]
Sorry, I forgot to release the update 😨 I've done it now, should be alive in couple of minutes :)

**Comment by sabriele** [comment]
Hi @dsznajder, thank you for addressing this issue earlier. I'm aware that you have fixed this already at
https://github.com/dsznajder/vscode-es7-javascript-react-snippets/blob/5065a7c978620414eeba65e6b67e9e41de496725/snippets/snippets.json#L1438

However, I'm still experiencing this issue:
![Screen Recording 2020-11-12 at 2 39 19 PM](https://user-images.githubusercontent.com/4678102/98905163-e99e8680-24f5-11eb-85bd-db3a01b4849e.gif)
 

I already am on v3.0.0:
![image](https://user-images.githubusercontent.com/4678102/98904407-819b7080-24f4-11eb-961d-8782c87c99d9.png)

I was wondering if you have any suggestions on how I could fix this? Thank you!

**Comment by rohitkrishna094** [comment]
Yeah useState uppercase issue still exists for me as well. Maybe we need to re-open another issue? Or maybe we are using it in a wrong way? the setxxx function is always lowercase.
