### ISSUE TITLE
Replace functions by arrow functions

### ISSUE THREAD

**Issue by Mlk777** [dsznajder/vscode-es7-javascript-react-snippets#67]
Hey, I know the issue had already been mentionned in #48 about **lifecycle methods using arrow function** in the documentation but not in the snippets.

What do you think about passing them to arrow functions ? Just to be consistent with the actual documentation.

**Comment by dsznajder** [comment]
@Mlk777 Hi, I thought about this but, they are bound inside `Component` / `PureComponent` so it would be repeating the action. I think I should update the docs. They are also easily recognized by this pattern so I think it's even useful

**Comment by Mlk777** [comment]
Sounds good thank you !
