### ISSUE TITLE
Extension not working at all

### ISSUE THREAD

**Issue by anthonybrown** [dsznajder/vscode-es7-javascript-react-snippets#70]
None of the snippets fire?

**Comment by dsznajder** [comment]
@anthonybrown Could you add some more details? I'm using it continuously day by day and it works for me.

**Comment by anthonybrown** [comment]
@dsznajder I fixed the issue.

**Comment by djnorrisdev** [comment]
@anthonybrown What did you do to fix it? On my Windows machine, I am having the same issue (I'm on latest VS Code version). On my Mac everything works out of the box, so I'm confused as to why it doesn't work on Windows.
