### ISSUE TITLE
Provide a PDF cheat sheet of all commands

### ISSUE THREAD

**Issue by Onra** [dsznajder/vscode-es7-javascript-react-snippets#8]

**Comment by anvarov** [comment]
yes it would be very useful

**Comment by dsznajder** [comment]
I can generate for now a pdf directly from markdown but it is not well formatted :/ If you have any ideas for that one, just leave it there

**Comment by jaredjgebel** [comment]
I made a PDF cheat sheet for myself, so I wanted to share. Feel free to pull it from my Google Docs here: [https://drive.google.com/file/d/1YtP6h_8o48lVloY6QgndeV_SiP15Z1ps/view?usp=sharing](url) 

I'm not sure if this kind of thing belongs in a pull request, but I'm happy to submit the PDF in one if necessary.

**Comment by dsznajder** [comment]
@jaredjgebel That would be also nice if you have some command with which I could regenerate it from README.md. If you have this, feel free to open PR. I will close it ASAP 💃

**Comment by kcloud99** [comment]
Could potentially set that up with either: 
https://www.npmjs.com/package/markdown-pdf
or 
https://www.npmjs.com/package/mdpdf

**Comment by stackerine** [comment]
The best deal would be to have a command to search in snippet.

**Comment by dsznajder** [comment]
Search Available in v2.0.0
