### ISSUE TITLE
Add styled-components import snippets

### ISSUE THREAD

**Issue by selrond** [dsznajder/vscode-es7-javascript-react-snippets#80]
styled-components is an extremely common import given it's the most popular css-in-js library.
It could look like this: `imsc` -> `import styled from 'styled-components'`

**Comment by dsznajder** [comment]
@selrond I would like to not add some packages as this kind of imports could be add nearly to every popular package. 
Sorry, but I never used styled-components commonly, only for some specific projects.

**Comment by selrond** [comment]
@dsznajder I understand that, but you already include redux for example - many people don't use redux at all.

**Comment by dsznajder** [comment]
@selrond Still redux is more than 3 times popular than `styled-components` :)
