### ISSUE TITLE
Functional arrow component with default props

### ISSUE THREAD

**Issue by danielo515** [dsznajder/vscode-es7-javascript-react-snippets#82]
Hey, thanks for this collection of snippets, it is really great.
I would love to not have to add default-props every time I bootstrap a component. Do you think that you can add an extra snippet that creates an arrow functional component with prop types and also default props? 
Thanks in advance.

**Comment by dsznajder** [comment]
@danielo515 Thanks for issue, but there is no `defaultProps` to any of components, so I would not add this as separate thing.

As idea you can add 
```js
defaultProps = {}
```

and
```js
${1:ComponentName}.defaultProps = {}
```

To snippets.

**Comment by danielo515** [comment]
Yes, in fact I have one.
But that requires me to type 50% more snippets than having it just on one 🤣
What about creating a version of all the existing snippets but with defaultProps?

**Comment by dsznajder** [comment]
@danielo515 If you can that would be awesome but I'm not sure about the name :) If you have any Idea just create a PR :)

**Comment by dsznajder** [comment]
@danielo515 This issue has lack of activity from any other users, I don't think it's needed :) Closing.
