### ISSUE TITLE
Make snippets usable with Emmet

### ISSUE THREAD

**Issue by DrunkenJanna** [dsznajder/vscode-es7-javascript-react-snippets#84]
Emmet is installed by default in VSCode, also very common is adding emmet to js files to support jsx. Your extension blocks that usability, for example you can't just write div and press tab to make a div html element.

**Comment by dsznajder** [comment]
@DrunkenJanna Are you sure that this is problem with extension? #55 Do you have option `Emmet: Trigger Expansion On Tab` enabled?

**Comment by DrunkenJanna** [comment]
Oof, sorry for the problem, I had emmet enabled for jsx only in last workspace not globally and I wasnt aware of that, im closing an issues
