### ISSUE TITLE
tsrafc does not contain a default export

### ISSUE THREAD

**Issue by impulse** [dsznajder/vscode-es7-javascript-react-snippets#88]
```ts
// tsrafc
import React from 'react'

interface Props {
  
}

export const App: React.FC<Props> = () => {
  return (
    <div>
      
    </div>
  )
}
```

Will be considered as faulty since not containing a default export. 

I'd suggest removing `tsrafc` since you cannot call `default export const X`.

**Comment by dsznajder** [comment]
@impulse removed in 2.5.0 :)

**Comment by drakang4** [comment]
What makes this being considered as faulty?
I personally prefer this way than `tsrafce` and didn't find any problem of it.

**Comment by impulse** [comment]
@drakang4 makes sense. Feel free to readd
