### ISSUE TITLE
return type for tsrfc/tsrfce should be React.ReactElement

### ISSUE THREAD

**Issue by Em-Ant** [dsznajder/vscode-es7-javascript-react-snippets#90]
After fixing #86 (thank you very much !!!), the return type is still wrong.`ReactElement` is under `React` namespace. It must be imported, or referred as `React.ReactElement`

(https://github.com/dsznajder/vscode-es7-javascript-react-snippets/blob/master/snippets/ts-snippets.json#L89)

**Comment by dsznajder** [comment]
@Em-Ant Sorry! I'm kinda new in whole typescript world :) I will fix it through this weekend :)

**Comment by impulse** [comment]
@Em-Ant the return type is not wrong. I just forgot to import ReactElement in my fix, sorry! Seems @dsznajder didn't have time so I am submitting a PR.
