### ISSUE TITLE
impt returns incorrect Import

### ISSUE THREAD

**Issue by horne3754sg** [dsznajder/vscode-es7-javascript-react-snippets#92]
When I type impt to import the propTypes it returns the following:

`import PropTypes from 'prop-types'`

but it should return propTypes with a lowercased p

`import propTypes from 'prop-types'`

**Comment by dsznajder** [comment]
@horne3754sg I disagree. Even in docs you have upper cased.
https://reactjs.org/docs/typechecking-with-proptypes.html
