### ISSUE TITLE
Only works once before having to restart VSCode

### ISSUE THREAD

**Issue by gjones604** [dsznajder/vscode-es7-javascript-react-snippets#97]
I love this extension and use it daily, but all of a sudden it only works once before I have to restart VSCode. Not really sure why, I've tried disabling all other extensions and the problem persists.

**Comment by nparoski** [comment]
I have this issue as well, it started happening few days ago.

Visual Studio Code version: 1.41.1, es7-javascript-react-snippets version 2.5.0

**Comment by JackieChan1994** [comment]
> I have this issue as well, it started happening few days ago. Maybe latest vscode update is causing trouble?
> 
> Visual Studio Code version: 1.41.1, es7-javascript-react-snippets version 2.5.0

I rollback vscode version to 1.40.1,and it works

**Comment by dsznajder** [comment]
Looks like issue in VSCode unfortunately. I search for issue but for now, I recommend using shortcut to trigger search menu (CMD + Shift + R on Mac).

**Comment by gjones604** [comment]
CTRL + Alt + R for Windows

**Comment by dsznajder** [comment]
@gjones604 Could you confirm this bug still exists in newest version of VSCode?

**Comment by gjones604** [comment]
Yes still an issue on 1.42.1

**Comment by gjones604** [comment]
Seems to be fixed now. Thanks!

**Comment by dsznajder** [comment]
@gjones604 I did nothing actually :P there was a bug inside VSCode :)

**Comment by nparoski** [comment]
@dsznajder Did you manage to resolve this issue or did you close it because its vscode bug?

**Comment by dsznajder** [comment]
@nparoski I did not meet this on my end. Also, if you look on previous comment, someone wrote that it's resolved now. I recommend you to update VSCode to newest version.

**Comment by nparoski** [comment]
@dsznajder Whoops sorry i overlooked that comment, thank you!
