### ISSUE TITLE
After update to latest version

### ISSUE THREAD

**Issue by ekaone** [dsznajder/vscode-es7-javascript-react-snippets#98]
Issue Type: <b>Bug</b>

After update my VS Code to latest version, React ES7 extension (snippets) can not working properly, show me how to use previous version..really can not working

Extension version: 2.5.0
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz (4 x 2993)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (9.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dsznajder** [comment]
#97
